#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="conjugateLmbFoam"

source /usr/lib/openfoam/openfoam2212/etc/bashrc

# fluid
runApplication -l log.blockMesh-fluid blockMesh
runApplication -l log.setSet-fluid setSet -batch setSet-fluid.batch
runApplication -l log.setsToZones-fluid setsToZones
runApplication setFields

#solid
runApplication -l log.blockMesh-solid blockMesh -region solid
runApplication -l log.setSet-solid setSet -region solid -batch setSet-solid.batch
runApplication -l log.setsToZones-solid setsToZones -region solid

source /home/ojm40/foam/foam-extend-5.0/etc/bashrc

runApplication $application
